### ISSUE TITLE
HTTP Basic Authentication not supported for ES (401 - Not Authorized)

### ISSUE THREAD

**Issue by diegojonio** [Alino/alino-mongo2es#6]
I'm trying to use http basic authentication to ES using the following format: https://es_user:es_password@es_url:es_port, but it's cutting out the authentication credentials before sending the resquest, which ends up returning 401.

It could work if you add an auth string option to ES obj when instanciating Mongo2ES.

``` javascript
options = {
  ES: {
    host: // String - url 
    auth: // String - 'username:password'       
  }
}
```

And then on every request you would foward the auth param to the request:

`````` javascript
HTTP.get(ES.host, {data: '/', auth: ES.auth});
```javascript
``````

**Comment by Alino** [comment]
Hi @diegojonio thank you, I have never done anything with authentication around ES yet.
Currently I am too busy to look at this.
Pull requests for this issue are welcome.

**Comment by diegojonio** [comment]
Hi @Alino, this problem is more related to HTTP than to ES. 

Would be a pleasure to contribute, could you just give some instructions on how to build, run and test the package?

I've tried meteor test-packages on the project Mongo2ES project but it shows 0 tests executed. 
I've also tried mocha --compilers coffee:coffee-script/register --ui bdd --reporter /reportPath/mochaIntellijReporter.js --recursive /projectPath/alino-mongo2es/tests/test.coffee but it complains about dependencies.

I'm adding one more parameter Meteor.settings.elasticsearchAuth or process.env.elasticsearchAuth and it will receive http credentials in the format 'username:password'. Those informations should not me hard coded.

**Comment by Alino** [comment]
Thank you for your contribution! I will write manual in the README on how to contribute, as soon as I will be less busy.

Merged.
